[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.1.7"
solana-sdk = "2.1.7"
spl-governance = "4.0.0"
borsh = "1.5.3"
borsh-derive = "1.5.3"
thiserror = "1.0.69"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []